=== sunilkumargonela9/Cypress/fixtures/global_qa/publicapi_get_relationship_resp_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "customerCode": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "capitalClassCode": {
      "type": "string"
    },
    "creditRatingCode": {
      "type": "string"
    },
    "countryCode": {
      "type": "string"
    },
    "industryCode": {
      "type": "string"
    },
    "industryCategory": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "parentCustomerCode": {
      "type": "string"
    },
    "dateCreated": {
      "type": "string"
    },
    "createdBy": {
      "type": "string"
    },
    "updatedBy": {
      "type": "string"
    },
    "lastUpdatedUtc": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "customerCode",
    "name",
    "capitalClassCode",
    "creditRatingCode",
    "countryCode",
    "industryCode",
    "industryCategory",
    "description",
    "parentCustomerCode",
    "dateCreated",
    "createdBy",
    "updatedBy",
    "lastUpdatedUtc"
  ]
}

=== sunilkumargonela9/Cypress/fixtures/getrelationshipresp.json
{
  "id": "d0ae88e7-4b9b-4667-9085-08d85dc8b294",
  "customerCode": "RCANZ11",
  "name": "Alpha Consulting  Imported",
  "capitalClassCode": "Corp",
  "creditRatingCode": "D2",
  "countryCode": "AUS",
  "industryCode": "pbs-7862",
  "industryCategory": "pbs",
  "description": "Created through import process",
  "parentCustomerCode": "RCANZ11",
  "dateCreated": "2020-09-21T05:44:05.017588Z",
  "createdBy": "scott",
  "updatedBy": "scott",
  "lastUpdatedUtc": "2023-03-15T01:10:14.1923435Z"
}
