=== sunilkumargonela9/Cypress/fixtures/cba_qa/publicapi_get_deal_resp_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "uid": {
      "type": "string"
    },
    "scenarios": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "uid": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "isPrimary": {
              "type": "boolean"
            },
            "products": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "uid": {
                      "type": "string"
                    },
                    "productCode": {
                      "type": "null"
                    },
                    "name": {
                      "type": "string"
                    },
                    "isCrossSell": {
                      "type": "null"
                    },
                    "isFutureCrossSell": {
                      "type": "null"
                    },
                    "variantCode": {
                      "type": "string"
                    },
                    "variantName": {
                      "type": "string"
                    },
                    "feeLines": {
                      "type": "array",
                      "items": [
                        {
                          "type": "object",
                          "properties": {
                            "uid": {
                              "type": "null"
                            },
                            "code": {
                              "type": "string"
                            },
                            "name": {
                              "type": "string"
                            },
                            "standard": {
                              "type": "number"
                            },
                            "proposed": {
                              "type": "number"
                            },
                            "frequency": {
                              "type": "integer"
                            },
                            "isWaived": {
                              "type": "boolean"
                            },
                            "isAmortised": {
                              "type": "boolean"
                            },
                            "isOngoing": {
                              "type": "boolean"
                            },
                            "metaClassId": {
                              "type": "null"
                            },
                            "id": {
                              "type": "null"
                            }
                          },
                          "required": [
                            "uid",
                            "code",
                            "name",
                            "standard",
                            "proposed",
                            "frequency",
                            "isWaived",
                            "isAmortised",
                            "isOngoing",
                            "metaClassId",
                            "id"
                          ]
                        },
                        {
                          "type": "object",
                          "properties": {
                            "uid": {
                              "type": "null"
                            },
                            "code": {
                              "type": "string"
                            },
                            "name": {
                              "type": "string"
                            },
                            "standard": {
                              "type": "number"
                            },
                            "proposed": {
                              "type": "number"
                            },
                            "frequency": {
                              "type": "integer"
                            },
                            "isWaived": {
                              "type": "boolean"
                            },
                            "isAmortised": {
                              "type": "boolean"
                            },
                            "isOngoing": {
                              "type": "boolean"
                            },
                            "metaClassId": {
                              "type": "null"
                            },
                            "id": {
                              "type": "null"
                            }
                          },
                          "required": [
                            "uid",
                            "code",
                            "name",
                            "standard",
                            "proposed",
                            "frequency",
                            "isWaived",
                            "isAmortised",
                            "isOngoing",
                            "metaClassId",
                            "id"
                          ]
                        }
                      ]
                    },
                    "parentEntityId": {
                      "type": "null"
                    },
                    "parentEntityName": {
                      "type": "null"
                    },
                    "parentEntityType": {
                      "type": "null"
                    },
                    "metaClassId": {
                      "type": "string"
                    },
                    "id": {
                      "type": "string"
                    },
                    "annualSalesTurnover": {
                      "type": "number"
                    },
                    "bookingCentre": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "code": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "code"
                      ]
                    },
                    "commitmentDate": {
                      "type": "string"
                    },
                    "commitmentPeriod": {
                      "type": "integer"
                    },
                    "committedFacility": {
                      "type": "boolean"
                    },
                    "currency": {
                      "type": "string"
                    },
                    "externalUpfrontCosts": {
                      "type": "number"
                    },
                    "financialInstitutionRegulated": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "code": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "code"
                      ]
                    },
                    "interestRateFrequency": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "code": {
                          "type": "integer"
                        }
                      },
                      "required": [
                        "name",
                        "code"
                      ]
                    },
                    "interestRateType": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "code": {
                          "type": "integer"
                        }
                      },
                      "required": [
                        "name",
                        "code"
                      ]
                    },
                    "lgd": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "code": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "code"
                      ]
                    },
                    "limit": {
                      "type": "number"
                    },
                    "marginOverReferenceRate": {
                      "type": "number"
                    },
                    "pdRatingCode": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "code": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "code"
                      ]
                    },
                    "permInterestRateFrequency": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "code": {
                          "type": "integer"
                        }
                      },
                      "required": [
                        "name",
                        "code"
                      ]
                    },
                    "permInterestRateType": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "code": {
                          "type": "integer"
                        }
                      },
                      "required": [
                        "name",
                        "code"
                      ]
                    },
                    "permRepaymentType": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "code": {
                          "type": "integer"
                        }
                      },
                      "required": [
                        "name",
                        "code"
                      ]
                    },
                    "permResidualValue": {
                      "type": "number"
                    },
                    "productOwner": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "code": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "code"
                      ]
                    },
                    "productVariant": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "code": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "code"
                      ]
                    },
                    "prudentialCategory": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "code": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "code"
                      ]
                    },
                    "refRate": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "code": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "code"
                      ]
                    },
                    "repaymentFrequency": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "code": {
                          "type": "integer"
                        }
                      },
                      "required": [
                        "name",
                        "code"
                      ]
                    },
                    "repaymentType": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "code": {
                          "type": "integer"
                        }
                      },
                      "required": [
                        "name",
                        "code"
                      ]
                    },
                    "residualValue": {
                      "type": "number"
                    },
                    "residualValueAmount": {
                      "type": "number"
                    },
                    "subSegment": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "code": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "code"
                      ]
                    },
                    "utilisationRate": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "uid",
                    "productCode",
                    "name",
                    "isCrossSell",
                    "isFutureCrossSell",
                    "variantCode",
                    "variantName",
                    "feeLines",
                    "parentEntityId",
                    "parentEntityName",
                    "parentEntityType",
                    "metaClassId",
                    "id",
                    "annualSalesTurnover",
                    "bookingCentre",
                    "commitmentDate",
                    "commitmentPeriod",
                    "committedFacility",
                    "currency",
                    "externalUpfrontCosts",
                    "financialInstitutionRegulated",
                    "interestRateFrequency",
                    "interestRateType",
                    "lgd",
                    "limit",
                    "marginOverReferenceRate",
                    "pdRatingCode",
                    "permInterestRateFrequency",
                    "permInterestRateType",
                    "permRepaymentType",
                    "permResidualValue",
                    "productOwner",
                    "productVariant",
                    "prudentialCategory",
                    "refRate",
                    "repaymentFrequency",
                    "repaymentType",
                    "residualValue",
                    "residualValueAmount",
                    "subSegment",
                    "utilisationRate"
                  ]
                }
              ]
            },
            "metaClassId": {
              "type": "string"
            },
            "id": {
              "type": "string"
            }
          },
          "required": [
            "uid",
            "name",
            "isPrimary",
            "products",
            "metaClassId",
            "id"
          ]
        }
      ]
    },
    "statusCode": {
      "type": "string"
    },
    "statusName": {
      "type": "null"
    },
    "createdDate": {
      "type": "string"
    },
    "createdBy": {
      "type": "string"
    },
    "updatedDate": {
      "type": "string"
    },
    "updatedBy": {
      "type": "string"
    },
    "approvalActionInfo": {
      "type": "null"
    },
    "dealCode": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "customerName": {
      "type": "string"
    },
    "customerCode": {
      "type": "string"
    },
    "userCode": {
      "type": "null"
    },
    "metaClassId": {
      "type": "string"
    },
    "id": {
      "type": "string"
    }
  },
  "required": [
    "uid",
    "scenarios",
    "statusCode",
    "statusName",
    "createdDate",
    "createdBy",
    "updatedDate",
    "updatedBy",
    "approvalActionInfo",
    "dealCode",
    "name",
    "customerName",
    "customerCode",
    "userCode",
    "metaClassId",
    "id"
  ]
}

=== sunilkumargonela9/Cypress/fixtures/getdealdetailsresp.json
{
  "uid": "a7f36b5d-f2a6-48f5-dcd1-08db24ef67df",
  "scenarios": [
    {
      "uid": "d774f4dc-31c2-4e83-3524-08db24ef6827",
      "name": "Scenario 1",
      "isPrimary": true,
      "products": [
        {
          "uid": "16e04174-edfa-43b2-6c49-08db24ef6846",
          "productCode": null,
          "name": "Term Loan",
          "isCrossSell": null,
          "isFutureCrossSell": null,
          "variantCode": "loan-tl",
          "variantName": "Term Loan",
          "feeLines": [
            {
              "uid": null,
              "code": "EstabFeeCredit",
              "name": "Establishment Fee",
              "standard": 0.005,
              "proposed": 0.005,
              "frequency": 1,
              "isWaived": false,
              "isAmortised": true,
              "isOngoing": false,
              "metaClassId": null,
              "id": null
            },
            {
              "uid": null,
              "code": "LineFeeCredit",
              "name": "Line Fee",
              "standard": 0.05,
              "proposed": 0.05,
              "frequency": 2,
              "isWaived": false,
              "isAmortised": false,
              "isOngoing": true,
              "metaClassId": null,
              "id": null
            }
          ],
          "parentEntityId": null,
          "parentEntityName": null,
          "parentEntityType": null,
          "metaClassId": "Dpx.Products.Lending",
          "id": "16e04174-edfa-43b2-6c49-08db24ef6846"
        }
      ],
      "metaClassId": "Dpx.Pricing.Scenario",
      "id": "d774f4dc-31c2-4e83-3524-08db24ef6827"
    }
  ],
  "statusCode": "draft",
  "statusName": null,
  "createdDate": "2023-03-15T01:53:23.1075599Z",
  "createdBy": "admin",
  "updatedDate": "2023-03-15T01:53:23.0972874Z",
  "updatedBy": "admin",
  "approvalActionInfo": null,
  "dealCode": "1678845201",
  "name": "Public API Test Deal1678845201",
  "customerName": "Alpha Consulting  Imported",
  "customerCode": "RCANZ11",
  "userCode": null,
  "metaClassId": "Dpx.Pricing.Deal",
  "id": "a7f36b5d-f2a6-48f5-dcd1-08db24ef67df"
}
